# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IU-Day1pgHxaTqzfqdYLez-i5LFaC76C
"""

from google.colab import drive

drive.mount('/content/drive')

!cp drive/MyDrive/LouayML/data.py .
!cp drive/MyDrive/LouayML/train.py .
!cp drive/MyDrive/LouayML/helpers.py .
!cp drive/MyDrive/LouayML/CNN_model.py .
!cp drive/MyDrive/LouayML/Unet_model.py .

import numpy as np 
import os
import sys
import skimage.io as io
import skimage.transform as trans
import numpy as np

import tensorflow as tf 
from tensorflow import keras
import data
from helpers import *
import train


#to train
model=train.train_model('Unet') #Or CNN

## to load models
modelpath='/models/model_name'
model=keras.Models.load(modelpath)